### ISSUE TITLE
Fix stochastic test failures

### ISSUE THREAD

**Issue by jchodera** [bhmm/bhmm#43]
```
======================================================================
FAIL: test_discrete_4_2 (bhmm.tests.test_init_discrete.TestHMM)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/_test/lib/python3.5/site-packages/bhmm-0.6.1+22.g6f0de1e-py3.5-linux-x86_64.egg/bhmm/tests/test_init_discrete.py", line 85, in test_discrete_4_2
    assert(np.max(B-Bref) < 0.05 or np.max(B[[1, 0]]-Bref) < 0.05)
AssertionError
----------------------------------------------------------------------
```

Either set the random number seed to make this deterministic or use the statistical error and a 6-sigma tolerance in order to make these tests fail only when things are broken.

**Comment by jchodera** [comment]
Here's another one:

```
======================================================================
FAIL: test_2state_nonrev_step (bhmm.tests.test_bhmm_patho.TestBHMMPathological)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/_test/lib/python3.4/site-packages/bhmm-0.6.1+22.gcc92643-py3.4-linux-x86_64.egg/bhmm/tests/test_bhmm_patho.py", line 42, in test_2state_nonrev_step
    assert np.max(np.abs(sampled.transition_matrix_std[1])) < 1e-3
AssertionError
----------------------------------------------------------------------
```
